[build-system]
requires = ["setuptools", "setuptools_scm","numpy"]
build-backend = "setuptools.build_meta"

[project]
name = "PyDepManger"
dynamic = ["version"] 


# Package Dir
[tool.setuptools.packages.find]
where = ["PyDepManger","PyDepManger.*"]
namespaces = false


