[build-system]
requires = ["setuptools", "setuptools_scm", "numpy"]
build-backend = "setuptools.build_meta"

[project]
name = "PyDepManger"
dynamic = ["version"] 
dependencies = [
"pandas",
"numpy"
]

# Package Dir
[tool.setuptools.packages.find]
include = ["PyDepManger", "PyDepManger.*"]
namespaces = false

